### ISSUE TITLE
Got an issue using your gui.

### ISSUE THREAD

**Issue by D1s0fy** [ZeusJunior/tf2-automatic-gui#97]
`tf2-automatic-gui v2.2.2 is starting...

listening on port 3000

Couldn't get defindex for item: Mann Co. Supply Crate Key

TypeError: pricelist.push is not a function
    at D:\TF2Bot\Gui\tf2-automatic-gui\app\pricelist.js:218:15

TypeError: pricelist.push is not a function
    at D:\TF2Bot\Gui\tf2-automatic-gui\app\pricelist.js:218:15

Couldn't get defindex for item:  The Nostromo Napalmer

Getting all prices...

Execution time: 9950ms

Got all prices, continuing...

Received an unhandled rejection.

Promise {
  <rejected> TypeError: pricelist.push is not a function
      at D:\TF2Bot\Gui\tf2-automatic-gui\app\pricelist.js:218:15
      at async Object.pricelist.addItems (D:\TF2Bot\Gui\tf2-automatic-gui\app\pricelist.js:111:19)
}
Please report this @ https://github.com/ZeusJunior/tf2-automatic-gui/issues/new
`

**Comment by ZeusJunior** [comment]
Are you using tf2autobot or tf2automatic, and if tf2autobot what version are you on

**Comment by D1s0fy** [comment]
That's an autobot, 4.2.7 version

**Comment by D1s0fy** [comment]
So. What should I do, what's my problem, actually?

**Comment by arik123** [comment]
Unfortunately, GUI will not work for you, because autobot uses different
pricelist structure since V4 ... there will be GUI for autobot ... hopefully
